### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by guangxingmao** [Basis-Cash/basiscash-protocol#18]
Hi team,
I have no intention to transfer 3000 usdt to a contract address . The contract address is: 0xa7ed29b253d8b4e3109ce07c80fc570f81b63696
Can u help me find it back ? I am really sorry for causing such an error.
My transaction hash is:
0x234668830b2efff882cd068424a27a1421e17ceb16b750cc65c736a69b39038b
If you can, please forward my address, I would be very grateful:
0x7c874010fe56324eb4935478b7b345547201cdf9

thanks,
Rainie

**Comment by fr-jerry-smith** [comment]
We have discord group check this link out. https://discord.gg/KaHckyUY Thank you
