### ISSUE TITLE
Basis-Cash Improvement Proposal #3: Creation of a Community Development Fund + Formal Audit

### ISSUE THREAD

**Issue by yyctrader** [Basis-Cash/basiscash-protocol#19]
BIP-3
Title: Creation of a Community Development Fund + Formal Audit
Author:  @yyctrader
Category: Economic

**Simple Summary**
The author proposes to allocate 2% of future seigniorage to a newly created Community Development Fund (not to be confused with the Basis Cash Treasury, which is integral to the stabilization mechanism and will continue to function as before).

If passed, the process of engaging formal auditor(s) will commence immediately.

**Motivation**
With the ongoing success of the bootstrapping phase of the Basis Cash protocol, it is imperative that we continue to build on our positive momentum by investing in the growth of the platform. As we continue to feast upon some ungodly yields, we must not lose sight of the ultimate goal: to foster adoption and have Basis Cash become the premier decentralized algorithmic stablecoin in DeFi. Attempting to reach this goal will only be possible through building a vibrant community of contributors and fostering partnerships throughout the DeFi ecosystem.

The Community Development Fund will enable the Basis Cash protocol to cover operational expenses, fund a marketing budget, hire new team members as required, and incentivize community contributors through grants etc. 

The funds will be secured by a 48-hour timelock until the launch of V2, at which time it is envisioned that we will transition to a community-controlled multi-signature wallet.

If passed, the author proposes that the first use of the Community Fund will be to commission a formal audit of the Basis Cash Protocol. In light of the heavy demand across the industry, it is essential that we start the audit process as soon as possible.

**Specification**
We are proposing to implement one primary change:
1.	**2% of future Seigniorage will be transferred to a newly created Community Development Fund.**

**Comment by wang820203420** [comment]
why 2%？or 1%。I think the need to conduct a preliminary financial estimates.Then adjust gradually.Such as the first year in the second year of 0.2, 0.4. Like this.

**Comment by wang820203420** [comment]
Now don't know what's your operating costs?

**Comment by lgutonk** [comment]
This looks great, fully supportive. I don't see the 1m cap that was discussed? Also, how do we vote? Snapshot?

**Comment by lgutonk** [comment]
But if team thinks it's best to go with uncapped for now, supportive too. Great work with everything!
