### ISSUE TITLE
Basis-Cash Improvement Proposal #5: Lowering Seignorage TWAP Threshold

### ISSUE THREAD

**Issue by liquidityking** [Basis-Cash/basiscash-protocol#25]
BIP-5
Title: Lowering Seignorage TWAP Threshold
Author: liquidity_king, @liquidity_king
Category: Economic

**Summary:**
Currently, Basis Cash only mints additional BAC to BAS/BAB holders when the TWAP for BAC is over 1.05  This proposal is to lower the seignorage threshold to a lower value voted on by the community.

**Motivation:**
Early on in an algo coins lifecycle, investors are primarily speculators who are betting on continued expansion, while having confidence that the bond mechanism backstop will encourage buying below peg. BAC does not have a natural source of demand, with demand primarily coming from speculation that the network will expand.
 
Speculators rely on the seignorage dynamic to support BAS prices, which ultimately drive demand for BAC. They take comfort that the BAB mechanism will support them when prices fall below peg. However, with the current parameter of 1.05 there is a gap from 1.0-1.05 where investors are not supported by the protocols incentives. Speculators buying BAC at 1.04 are not supported by BAB demand for another 4 cents, and they are also not going to be receiving any seignorage income from their farmed BAS. The 1.05 parameter also effects BAB redemptions, meaning that BAB buyers need to have faith that TWAP will reach 1.05 in a reasonable time frame. Lowering this threshold gives BAB more potency which is the most critical incentive for the protocols long term survival. Finally in the very long term having a more narrow threshold should help us target a more narrow peg which is the ultimate value proposition of the project.

**Voting Options for BAS/BAB Seignorage Threshold:**
*1.05 (current)
*1.04
*1.03
*1.025
*1.02
*1.01
*1.0

**Comment by jerry0202** [comment]
1000% support

**Comment by jerry0202** [comment]
i think 1.001 or 1 is ok !!!

**Comment by a0o2099** [comment]
1.01 perfect

**Comment by pokl88** [comment]
1.01

**Comment by Elma-Landro** [comment]
0,01

**Comment by yyy20119** [comment]
1.01 or 1.02
