### ISSUE TITLE
Basis cash improvement proposal #6

### ISSUE THREAD

**Issue by AngeloAdam** [Basis-Cash/basiscash-protocol#27]
BIP-6

Title: Bond Proposal
Author: angelo_bounty0x, dennet
Category: Economic (Bond Issuance)
Summary: Limiting bond minting

**Current protocol design:**

Whenever the 1 hour TWAP (Time Weighted Average Price) of the $BAC price is below $1, unlimited Basis Bonds (hereinafter “$BAB”) can be minted at a discount. The discount is determined by the 1 hour TWAP. With a Basis Cash oracle price of P DAI, bonds are sold off at a price of P BAC (effective price being P^2 DAI), promising bond holders a premium when redeemed. For example, when the TWAP is $0.9 , then it is possible to mint one $BAB by burning 0.9 $BAC. A speculator can purchase $0.9 $BAC for $0.81 DAI, burn 0.9 BAC for 1 BAB, resulting in an effective price of 1 BAB = 0.81 DAI. 

**Problem**

Unlimited $BAB issuance capacity will lead to over issuance of $BAB debt. There is likely to be a time lag between the reduction in supply caused by $BAB issuance, and the twap price adjustment towards $1. The one hour window between each twap adjustment guarantees an unlimited amount of $BAB bonds will be available for speculators to purchase as long as demand exists. 

The Basis protocol should disincentivize issuance of unnecessary $BAB debt because long term overissuance of debt will lead to numerous protocol risks and vulnerabilities, including but not limited to the following:

1. A decline in value of $BAS. Only when the level of debt no longer exceeds the treasury balance will $BAS resume receiving seigniorage rewards. If there is a large pool of outstanding debt to be redeemed then there will be an increasingly long wait period for $BAS holders to resume receiving $BAS seigniorage rewards. This will result in a decline in $BAS price, as the present value of $BAS will be reduced. 

2. A larger pool of outstanding $BAB Bond debt. A rapidly increasing debt pool will result in reduced demand to purchase new bonds, due in part to a longer bond redemption waiting period. In order to offset increasingly lengthy redemption time a correspondingly larger bond discount will be needed to entice new bond purchasers. If the debt issuance outpaces debt redemption there is a greater risk of systemic protocol failure due to inability to repay outstanding debt.

3. Over contraction of the $BAC supply: Over issuance of $BAB will result in an over contraction of the $BAC supply, resulting in increased volatility as the over contracted supply of $BAC will swing in the opposite direction, above $1 necessitating further issuance of $BAC to expand the supply. This instability hinders the chief goal of the protocol which is to provide consistent price stability.

4. Opportunity for bad actors: An unlimited $BAB issuance enables an attack vector whereby bad actors artificially manipulate price to below $1 in order to purchase a large quantity of $BAB bonds at a discount.

**Proposed Solution:**

This proposal suggests altering the bond issuance mechanism by setting a maximum bond issuance cap. The cap will be of the following size: ($1-1hTWAP)*(Circ $BAC), where 1hTWAP is the 1h TWAP of the $BAC price and “Circ $BAC” is the Circulating $BAC supply. The cap will last for one hour; after an hour a new TWAP will be calculated and the cap is reset based on the new TWAP value.

**Comment by senamakel** [comment]
I'd suggest for the cap could be reset every 24 hours instead of every one hour as resetting the cap won't be as effective if the opportunity to mint BAC happens once every 24hours.

As per the current implementation, say if the protocol is off by 5%, and say a supply of 10,000 BAC; then a cap of 500 BAB is made and now the protocol is allowed to increase its debt by 5%.

However, since the debt cannot be fulfilled until the next 24-hour epoch and if the protocol is in its expansion phase, we are still allowing for more debt to be created (although not as much freely as it was before). 

For reference: existing elastic stablecoin protocols such as ESD, issue debt once per epoch.

**Proposed Solution**: Keep everything as it is, but instead calculate the epochs for `_updateConversionLimit` based on 24hrs instead of 1hr.
