### ISSUE TITLE
Cannot open the basis.cash documentation

### ISSUE THREAD

**Issue by Shing-Ho** [Basis-Cash/basiscash-protocol#29]
https://github.com/Basis-Cash/basiscash-protocol/blob/master/docs.basis.cash
basis.cash documentation giving me 404 error

**Comment by fr-jerry-smith** [comment]
> https://github.com/Basis-Cash/basiscash-protocol/blob/master/docs.basis.cash
> basis.cash documentation giving me 404 error

use https://docs.basis.cash
