### ISSUE TITLE
contract addresses?

### ISSUE THREAD

**Issue by steveklebanoff** [Basis-Cash/basiscash-protocol#6]
It would be ideal if in this repo or readme there was a list of contract addresses for what has been deployed on mainnet.

Does this exist? If not - would love to see it

**Comment by fr-jerry-smith** [comment]
I'll add it to readme.md

**Comment by fr-jerry-smith** [comment]
8f470c3c18b3ff4ca331b68fa2e8f9ce9fec9004 :)

**Comment by steveklebanoff** [comment]
thx!
